name: .NET CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: dotnet build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: dotnet build
        run: dotnet build --no-restore /p:TreatWarningsAsErrors="true"

  test:
    name: dotnet test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: dotnet test
        run: dotnet test --no-restore --verbosity normal

  format:
    name: dotnet format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: dotnet format
        run: dotnet format --verify-no-changes --severity error
